proxy:
  http: "http://example.com:8080"
  https: "http://example.com:8080"
  ALL: socks5://127.0.0.1:7890
plugin:
  Welcome: true
  ChatGPT: {}
auth_token: "your_token_here"
qq:
  port: 5501
  id: 123456789
admin:
  - 123
  - 456
name: "Aldotai"
